version: '3.3'

services:
  java_app:
    container_name: test_app
    image: whatever-java
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=jdbc:postgresql://java_db:5432/postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=test1234
    depends_on:
      - java_db
  java_db:
    container_name: some-postgres2
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test1234
      POSTGRES_DB: postgres
    volumes:
      - C:/Program Files/PostgreSQL/14/data/ForStuffs:/var/lib/postgresql/data

